rly_file = "Liverpool Area.rly"
ttb_files = [ "Liverpool Area.ttb",]
img_files = []
doc_files = [ "README.md",]
release_date = "2024-08-21"
version = "1.0.0"
country_code = "GB"
factual = true
description = ""
year = 2024
display_name = "Liverpool Area"
name = "Liverpool Area"
signal_position = "left"
author = "AlbertBall"
contributors = []
ssn_files = [ "Liverpool Lime Street prestart session.ssn",]
