rly_file = "Liverpool Lime Street.rly"
ttb_files = [ "Liverpool Lime Street.ttb",]
img_files = [ "Liverpool Lime Street.jpg",]
doc_files = [ "Liverpool Lime Street.pdf",]
release_date = "2024-09-xx"
version = "1.0.0"
country_code = "GB"
factual = true
description = ""
year = 2024
display_name = "Liverpool Lime Street"
name = "Liverpool Lime Street"
signal_position = "left"
author = "RailOS DevTeam"
contributors = []
ssn_files = [ "Liverpool Lime Street prestart session.ssn",]
